server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hanvita/spring-cloud-config-example-config.git
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: 10.162.4.171
    port: 5672
    username: rabbitmq
    password: rabbitmq

management:
  security:
    enabled: false
